#!/bin/bash

#export PATH=$PATH:/home/marc/work/opt/gcc-linaro-4.9-2014.11-x86_64_aarch64-linux-gnu/bin
#export CROSS_COMPILE=aarch64-linux-gnu-

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabihf-

@echo "follow instructions as per the README file, then"
@echo "put the board in recovery mode by powering up"
@echo "while holding both RECOVERY+RESET buttons"
@echo "sudo ./tegra-uboot-flasher flash jetson-tk1"

