#!/bin/bash

#export PATH=$PATH:/home/marc/work/opt/gcc-linaro-4.9-2014.11-x86_64_aarch64-linux-gnu/bin
#export CROSS_COMPILE=aarch64-linux-gnu-

export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabihf-

