#!/bin/bash
# this requires file ~/.lavarc to be properly configured, for instance:
#
#powerci@powerci:~/POWERCI/scripts/lava-ci$ cat ~/.lavarc 
#[baylibre]
#server: http://lava.baylibre.com:10080/RPC2/
#username: powerci
#token: om0ossq3crae53e7i6gb8rggkks0jb8i2ghexnnpw6x0t59mkembja8enhjp04cjuldo3eghnd6dc6dle18f1wrd0eiwjrorr06kputl2ac7t4quk966walf0xy19b1f
#

#lava-job-runner.py  --server http://lava.baylibre.com:10080/RPC2/ --stream /anonymous/powerci/ --section baylibre  --poll lab-baylibre-`date -I`.json
lava-job-runner.py  --section baylibre  --poll lab-baylibre-`date -I`.json

