#!/bin/sh
DEV=$1
BAUD=${2:-115200}

CU_LOCAL=/usr/local/bin/cu
CU_MAIN=/usr/bin/cu

if [ -e $CU_LOCAL ];then
    CU=$CU_LOCAL
elif [ -e $CU_MAIN ];then
    CU=$CU_MAIN
else
    echo "ERROR no such file $CU_LOCAL or $CU_MAIN"
    exit 1
fi

while true; do
  #
  # NOTE: cu src needs mofication to add --nortscts option
  # c.f. Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=336996
  #
  if [ -z "`$CU --help | grep nortscts`" ]; then
      test -e $DEV && $CU -l $DEV -s $BAUD --parity=none --nostop dir
  else
      test -e $DEV && $CU -l $DEV -s $BAUD --parity=none --nostop --nortscts dir
  fi

  if [ $? -ne 0 ];then
      echo "ERROR during cu-loop execution"
      exit 1
  fi

  sleep 0.5
done
