#!/bin/sh
DEV=$1
BAUD=${2:-115200}

CU_LOCAL=/usr/local/bin/cu
CU_MAIN=/usr/bin/cu

CU=$CU_LOCAL

NORTSCTS="--nortscts"
if [ -z "`$CU --help | grep '\-\-nortscts'`" ]; then
    NORTSCTS=""
fi

while true; do
  #
  # NOTE: cu src needs mofication to add --nortscts option
  # c.f. Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=336996
  #
  if [ -e $DEV ]; then
      $CU -l $DEV -s $BAUD --parity=none --nostop $NORTSCTS dir
      if [ $? -ne 0 ];then
          echo "ERROR during cu-loop execution"
          exit 1
      fi

  fi
  #test -e $DEV && $CU_LOCAL -l $DEV -s $BAUD --parity=none --nostop --nortscts dir
  sleep 0.5
done
