#!/bin/sh
DEV=$1
BAUD=${2:-115200}

while true; do
  #
  # NOTE: cu src needs mofication to add --nortscts option
  # c.f. Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=336996
  #
  test -e $DEV && /usr/local/bin/cu -l $DEV -s $BAUD --parity=none --nostop --nortscts dir
  sleep 0.5
done
